spring:
    application:
        name: musico-service
    datasource:
        url: jdbc:postgresql://banco-svc:5432/musico
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver
    h2:
        console:
            enabled: true
    jpa:
        show-sql: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        defer-datasource-initialization: true
server: 
  port: 8080
management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "health, info, metrics, prometheus"
  health:
    redis:
      enabled: false

