apiVersion: v1
kind: Service
metadata:
  namespace: musicoapp
  name: banco-monitoramento-svc
spec:
  type: NodePort
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 9187
      targetPort: 9187
      nodePort: 30008
