apiVersion: v1
kind: Service
metadata:
  namespace: musicoapp
  name: banco-svc
spec:
  type: NodePort
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
