apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: banco-pvc
  namespace: musicoapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: local-storage
