apiVersion: v1
kind: Service
metadata:
  name: musico-svc
  namespace: musicoapp
spec:
  selector:
    app: musico
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30010
  type: NodePort
