apiVersion: v1
kind: PersistentVolume
metadata:
  name: musico-pv
  namespace: musicoapp
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /home/paulo/docker-atividade/ContratacaoMusico/musico/k8s/data
