apiVersion: v1
kind: Service
metadata:
  namespace: musicoapp
  name: grafana-svc
spec:
  type: NodePort
  selector:
    app: monitoramento
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30009
