apiVersion: v1
kind: Service
metadata:
  namespace: musicoapp
  name: prometheus-svc
spec:
  type: ClusterIP
  selector:
    app: monitoramento
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
