apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: musicoapp
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/home/paulo/docker-atividade/ContratacaoMusico/musico/prometheus"
