global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"
  - job_name: "app-musico"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:30010"]
        labels:
          app: "app-musico"
  - job_name: "postgres"
    static_configs:
      - targets: ["host.docker.internal:30008"]
        labels:
          app: "postgres"
