name: deploy_musicoapp
on:
  push:
    branches:
      - "main"
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"
      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: "3.6.3"
      - name: Show ENVS
        run: |
          java -version
          mvn -version
      - name: Clean directory
        run: mvn clean
      - name: Run tests
        run: mvn test
      - name: Build project
        run: mvn package -DskipTests
      - name: Copy artefact
        run: |
          cp target/*.jar Docker/app.jar
      - name: Build Docker image
        run: docker build . -f Docker/Dockerfile -t musico:3.0
      - name: Create tag 3.0
        run: docker tag musico:3.0 paulopalmuti/musico:3.0
      - name: Create tag latest
        run: docker tag musico:3.0 paulopalmuti/musico:latest
      - name: Docker login
        run: |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USER }} --password-stdin
      - name: Docker push 3.0
        run: docker push paulopalmuti/musico:3.0
      - name: Docker push latest
        run: docker push paulopalmuti/musico:latest
      - name: Update k8s
        run: kubectl rollout restart deploy musico-deploy -n musicoapp
      - name: Deploy status
        run: kubectl rollout status deploy musico-deploy -n musicoapp
