name: deploy_musicoapp
on:
  push:
    branches:
      - "main"
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"
      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: "3.6.3"
      - name: Show ENVS
        run: |
          java -version
          mvn -version
      - name: Clean directory
        run: mvn clean
      - name: Run tests
        run: mvn tests
